spring:
  application:
    name: tokenCheckService


eureka:
  client:
    service-url:
      defaultZone: https://eurekaserverservice.onrender.com/eureka
  instance:
    prefer-ip-address: true    


server:
  port: 8084
